{% set name = "agrossuite" %}
{% set version = "2022.1.1.70391" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/agrossuite-{{ version }}.tar.gz
  sha256: 2f664df69ebe8366ee1de57c5796b8a3f99e85dd90c2de7aea4309f3eb324ef1

build:
  skip: True  # [win or osx]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =3.9
  run:
    - python =3.9

test:
  imports:
    - agrossuite
  commands:
    - pytest-3 --disable-warnings --durations=0 -v agrossuite

about:
  home: http://www.agros2d.org/
  summary: Multiplatform application for the solution of physical problems based on the deal.II library
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - artap-framework
