{% set name = "artap" %}
{% set version = "2022.1.1.1759" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/artap-{{ version }}.tar.gz
  sha256: c388ad4415d905464921e0f3a20a3be9f856c4b4d1cda8c3c6c8a84c71975521

build:
  skip: true  # [win or osx]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - appdirs
    - cython
    - joblib
    - matplotlib
    - nlopt
    - numpy >=1.13.3
    - pydoe2
    - python
    - rpyc
    - salib
    - scikit-learn
    - scipy
    - setuptools
    - six
    - smt
    - tensorflow

test:
  imports:
    - artap
  commands:
    - pytest --disable-warnings --durations=0 -v artap

about:
  home: http://www.agros2d.org/artap/
  summary: Platform for robust design optimization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - artap-framework
